# Specify the Docker image to use for the runner
image: docker:20.10.16

# Define services needed for the job
services:
  - docker:20.10.16-dind

# Define variables
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay
  TARGET_IMAGE: savantripathi22/tp_ai
  TARGET_TAG: june_10_1

# Define stages
stages:
  - docker

# Define jobs
docker-build:
  stage: docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  # Define any commands to run before the script
  before_script:
    # Uncomment and add commands here if needed
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    # Build the Docker image
    - docker build -t tp_ai -f Dockerfile .
    # Tag the Docker image
    - docker tag tp_ai $TARGET_IMAGE:$TARGET_TAG
    # Print Docker images to verify
    - docker images

    - docker push $TARGET_IMAGE:$TARGET_TAG

    
